/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_ProgrammingLang;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import JDBC_connection.ConnectionProvider;


/**
 *
 * @author fekede alemayehu
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        TabbedPanels = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        programmingLangTable = new javax.swing.JTable();
        RemovePanel = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        search_remove_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        remove_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Pl_id_remove = new javax.swing.JLabel();
        Pl_name_remove = new javax.swing.JLabel();
        Pl_author_remove = new javax.swing.JLabel();
        Search_remove_btn1 = new javax.swing.JButton();
        AddPanel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Pl_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Pl_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Pl_author = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AddPlButton = new javax.swing.JButton();
        ModifyPanel = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        search_modify_id = new javax.swing.JTextField();
        Search_modify_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Pl_id_modify = new javax.swing.JTextField();
        Pl_name_modify = new javax.swing.JTextField();
        Pl_author_modify = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Modify_btn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 0));
        setLocation(new java.awt.Point(300, 600));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Italianate", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 204, 0));
        jTextField1.setText("MENUS");
        jTextField1.setFocusable(false);
        jTextField1.setOpaque(false);
        jTextField1.setRequestFocusEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 42, 132, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Italianate", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 0));
        jButton2.setText("1, Add New PL ");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Italianate", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 153, 0));
        jButton3.setText("2. Modify PL");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Italianate", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 153, 0));
        jButton4.setText("3. Remove PL");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Italianate", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 153, 0));
        jButton5.setText("4. View All PL");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 380));

        jPanel7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel7ComponentShown(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        programmingLangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(programmingLangTable);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 430, 350));

        TabbedPanels.addTab("View All", jPanel7);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(search_remove_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, -1));

        jLabel5.setText("Enter ID to Remove:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, 20));

        remove_btn.setText("Remove");
        remove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_btnActionPerformed(evt);
            }
        });
        jPanel4.add(remove_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel12.setText("PL ID:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 60, 20));

        jLabel13.setText("PL Name:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 60, 20));

        jLabel14.setText("PL Author:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 60, 20));

        Pl_id_remove.setText("XXXXXXX");
        jPanel4.add(Pl_id_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 60, 20));

        Pl_name_remove.setText("XXXXXXX");
        jPanel4.add(Pl_name_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 60, 20));

        Pl_author_remove.setText("XXXXXXX");
        jPanel4.add(Pl_author_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 60, 20));

        Search_remove_btn1.setText("Search");
        Search_remove_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_remove_btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(Search_remove_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        RemovePanel.addTab("tab1", jPanel4);

        TabbedPanels.addTab("Remove", RemovePanel);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Add New Programming Languages:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, -1));
        jPanel2.add(Pl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, -1));

        jLabel2.setText("PL ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, 20));
        jPanel2.add(Pl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 110, -1));

        jLabel3.setText("PL Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, 20));

        Pl_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pl_authorActionPerformed(evt);
            }
        });
        jPanel2.add(Pl_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 110, -1));

        jLabel4.setText("PL Author:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 60, 20));

        AddPlButton.setText("Add");
        AddPlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AddPlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 90, 30));

        AddPanel.addTab("", jPanel2);

        TabbedPanels.addTab("Add", AddPanel);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(search_modify_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, -1));

        Search_modify_btn.setText("Search");
        Search_modify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_modify_btnActionPerformed(evt);
            }
        });
        jPanel5.add(Search_modify_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel7.setText("Enter ID to Modify:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, 20));
        jPanel5.add(Pl_id_modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, -1));
        jPanel5.add(Pl_name_modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, -1));

        Pl_author_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pl_author_modifyActionPerformed(evt);
            }
        });
        jPanel5.add(Pl_author_modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, -1));

        jLabel9.setText("PL Author:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 60, 20));

        jLabel10.setText("PL Name:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 60, 20));

        jLabel11.setText("PL ID:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 60, 20));

        Modify_btn.setText("Modify");
        Modify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modify_btnActionPerformed(evt);
            }
        });
        jPanel5.add(Modify_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 90, 30));

        ModifyPanel.addTab("tab1", jPanel5);

        TabbedPanels.addTab("Modify", ModifyPanel);

        getContentPane().add(TabbedPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 430, 390));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            TabbedPanels.setSelectedIndex(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        TabbedPanels.setSelectedIndex(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            TabbedPanels.setSelectedIndex(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            TabbedPanels.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void AddPlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlButtonActionPerformed
        try {
            String idString=Pl_id.getText();
            int id=Integer.parseInt(idString);
            String name=Pl_name.getText();
            String author=Pl_author.getText();
            //  new ProgrammingLanguage_1(id, name, author);
            System.out.println(id + " " + name + " " + author);
            Connection con = ConnectionProvider.getCon();
            Statement st=con.createStatement();
            //             String sql="INSERT INTO pl_table(Pl_ID,Pl_Name,Pl_Author) VALUES ('3','java', 'Barne');";
            String sql="INSERT INTO pl_table(Pl_ID,Pl_Name,Pl_Author) VALUES ('"+id+"','"+name+"', '"+author+"');";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "New Programming Language successfully Added to the System!");

            // TODO add your handling code here:
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_AddPlButtonActionPerformed

    private void Pl_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pl_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pl_authorActionPerformed

    private void Search_remove_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_remove_btn1ActionPerformed
        String SearchId = search_remove_id.getText();

        try{
            Connection con =ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select* from pl_table where Pl_ID ='"+SearchId+"'");
            if (rs.next()){
                Pl_id_remove.setText(rs.getString("pl_ID"));
                Pl_name_remove.setText(rs.getString("pl_Name"));
                Pl_author_remove.setText(rs.getString("pl_Author"));
            }else{
                JOptionPane.showMessageDialog(null, "No Programming Language with this ID");
            };

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_remove_btn1ActionPerformed

    private void remove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_btnActionPerformed
        String SearchId=search_remove_id.getText();
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("delete FROM pl_table WHERE pl_ID ='"+SearchId+"'");
            Pl_author_remove.setText("");
            Pl_id_remove.setText("");
            Pl_name_remove.setText("");
            JOptionPane.showMessageDialog(null, "successfuly deleted ");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_remove_btnActionPerformed

    private void Modify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modify_btnActionPerformed
        String plId =Pl_id_modify.getText();
        String author = Pl_author_modify.getText();
        String name=Pl_name_modify.getText();
        try{
            Connection con =ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("update pl_table set pl_ID='"+plId+"',pl_Name='"+name+"',pl_Author='"+author+"'");
            JOptionPane.showMessageDialog(null, "successfully updated");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Modify_btnActionPerformed

    private void Pl_author_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pl_author_modifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pl_author_modifyActionPerformed

    private void Search_modify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_modify_btnActionPerformed
        String SearchId = search_modify_id.getText();

        try{
            Connection con =ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select* from pl_table where Pl_ID ='"+SearchId+"'");
            if (rs.next()){
                Pl_id_modify.setText(rs.getString("pl_ID"));
                Pl_name_modify.setText(rs.getString("pl_Name"));
                Pl_author_modify.setText(rs.getString("pl_Author"));
            }else{
                JOptionPane.showMessageDialog(null, "No Programming Language with this ID");
            };

        }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Search_modify_btnActionPerformed

    private void jPanel7ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel7ComponentShown
try{Connection con = ConnectionProvider.getCon();
    Statement st = con.createStatement();
    ResultSet  rs= st.executeQuery("select * from pl_table");
    programmingLangTable.setAutoResizeMode(programmingLangTable.AUTO_RESIZE_OFF);
//    programmingLangTable.setModel(DbUtils.resultSetToTableModel(rs));
    
    
}catch (Exception e){
  JOptionPane.showConfirmDialog(null, "Failed to Fetch Data");
} 
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AddPanel;
    private javax.swing.JButton AddPlButton;
    private javax.swing.JTabbedPane ModifyPanel;
    private javax.swing.JButton Modify_btn;
    private javax.swing.JTextField Pl_author;
    private javax.swing.JTextField Pl_author_modify;
    private javax.swing.JLabel Pl_author_remove;
    private javax.swing.JTextField Pl_id;
    private javax.swing.JTextField Pl_id_modify;
    private javax.swing.JLabel Pl_id_remove;
    private javax.swing.JTextField Pl_name;
    private javax.swing.JTextField Pl_name_modify;
    private javax.swing.JLabel Pl_name_remove;
    private javax.swing.JTabbedPane RemovePanel;
    private javax.swing.JButton Search_modify_btn;
    private javax.swing.JButton Search_remove_btn1;
    private javax.swing.JTabbedPane TabbedPanels;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable programmingLangTable;
    private javax.swing.JButton remove_btn;
    private javax.swing.JTextField search_modify_id;
    private javax.swing.JTextField search_remove_id;
    // End of variables declaration//GEN-END:variables
}
